name = "JlDevUV"
uuid = "7f04729b-ef8a-45ad-bbde-f9800ff97cb0"
authors = ["SatoshiTerasaki <terasakisatoshi.math@gmail.com>"]
version = "0.1.0"

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
PythonCall = "0.9.24"

[extras]
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ReTestItems"]
